version: "3.7"
services:

  chute:
    container_name: chute
    image: golang:1.12.0-stretch
    environment:
      - GO111MODULE=on
    volumes:
      - .:/go/src/github.com/inf-rno/chute
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /go/src/github.com/inf-rno/chute
    entrypoint: go run cmd/chute/main.go
    networks:
      envoymesh:
        aliases:
          - chute
    expose:
      - "18000"
      - "18001"
      - "8001"
    ports:
      - "8888:8001"
      - "18000:18000"
      - "18001:18001"

  ingress-envoy:
    build:
      context: .
      dockerfile: Dockerfile-ingress
    volumes:
      - ./ingress-envoy.yaml:/etc/ingress-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - ingress-envoy
    expose:
      - "6379"
      - "8001"
    ports:
      - "6380:6379"
      - "8002:8001"

  egress-envoy:
    build:
      context: .
      dockerfile: Dockerfile-egress
    volumes:
      - ./egress-envoy.yaml:/etc/egress-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "6379"
      - "8001"
    ports:
      - "6379:6379"
      - "8001:8001"

  redis1:
    build:
      context: .
      dockerfile: Dockerfile-redis
    networks:
      envoymesh:
        aliases:
          - redis1
    expose:
      - "6379"
    ports:
      - "6381:6379"

  redis2:
    build:
      context: .
      dockerfile: Dockerfile-redis
    networks:
      envoymesh:
        aliases:
          - redis2
    expose:
      - "6379"
    ports:
      - "6382:6379"

networks:
  envoymesh: {}
