static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 6379
    filter_chains:
      filters:
        - name: envoy.redis_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy
            stat_prefix: ingress_envoy
            prefix_routes:
              routes:
                - prefix: "1:"
                  cluster: redis1
                - prefix: "2:"
                  cluster: redis2
              catch_all_route: 
                cluster: redis1
            settings:
              op_timeout: 5s              
      tls_context:
        common_tls_context:
          tls_certificates:
            - certificate_chain:
                filename: "/etc/certs/servercert.pem"
              private_key:
                filename: "/etc/certs/serverkey.pem"
          validation_context:
            trusted_ca:
                filename: "/etc/certs/cacert.pem"
            verify_certificate_hash: "90:CA:A3:E0:B0:AD:8E:E6:4F:BC:11:6C:7B:E5:9D:35:11:2B:46:71:5F:4D:5C:52:85:37:23:08:38:28:B4:D6"
  clusters:
  - name: redis1
    connect_timeout: 1s
    type: strict_dns
    lb_policy: MAGLEV
    load_assignment:
      cluster_name: redis1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: redis1
                port_value: 6379
  - name: redis2
    connect_timeout: 1s
    type: strict_dns
    lb_policy: MAGLEV
    load_assignment:
      cluster_name: redis2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: redis2
                port_value: 6379
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
